AWSTemplateFormatVersion: 2010-09-09
Description: Create Certificate.

Parameters:
  Domain:
      Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      ValidationMethod: DNS

Outputs:
  CertificateId:
    Value: !Ref Certificate
