AWSTemplateFormatVersion: 2010-09-09
Description: Create ElasticLoadBalancer Listener rule.

Parameters:
  ListenerId:
    Type: String
  TargetGroupId:
    Type: String
  CertificateArn:
    Type: String
  Domain:
    Type: String
  RulePriority:
    Type: String

Resources:
  # ロードバランサーのリスナーに対象サイトのSSL証明書を登録
  ListenerCertificate:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      Certificates:
        - CertificateArn: !Ref CertificateArn
      ListenerArn: !Ref ListenerId

  # サービス別にバランサのリスナーに対して、ルールを追加
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupId
      Conditions:
        - Field: host-header
          Values:
            - !Ref Domain
      ListenerArn: !Ref ListenerId
      Priority: !Ref RulePriority
